name: Test

on:
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always
  SBIO_LIB_PATH: test/lib/x86_64/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tsts
      run: cargo test --verbose
